import NavigationBar from "@/components/NavigationBar";
import "./globals.css";

import { ToastContainer } from "react-toastify";
import ClientProviders from "@/components/ClientProviders";
import BottomNav from "@/components/BottomNav";


export const metadata = {
  title: "BlogX",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
   
    <html lang="en">
      <body className="transition-colors duration-300 bg-white text-black dark:bg-gray-950 dark:text-white">
       
       
           <ClientProviders>
           <NavigationBar/>
             <ToastContainer theme="dark" />
             <div className="px-2 md:px-50 ">
          {children}
          </div>
          <div className="md:hidden">
             <BottomNav/>
          </div>
           
          
          
          </ClientProviders>
         
        
      </body>
    </html>
    
  );
}
